workflows:

  # Development Workflow
  development-workflow:
    name: Development Workflow - Android & iOS
    instance_type: mac_mini_m1
    max_build_duration: 120
    integrations:
      app_store_connect: Codemagic CICD
    triggering:
      events:
        - push
        - tag
      #       - pull_request
      branch_patterns:
        - pattern: dev-*
        - include: true
        - source: true
      tag_patterns:
        #       - pattern: build v+([0-9]).+([0-9]).+([0-9])
        - pattern: build*
        - include: true
      cancel_previous_builds: true

    # watched files/folders have changed since the last successful build
    #    when:
    #      changeset:
    #        includes:
    #          - '.'
    #          - 'android/'
    #        excludes:
    #          - '**/*.md'
    #      condition: not event.pull_request.labels[0].name == "codemagicTest"

    environment:
      flutter: 3.13.7
      java: 17
      cocoapods: default
      xcode: latest
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches


    scripts:
      - name: Set up local.properties
        script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties" # Set Flutter SDK path for Android project

      - name: Get Flutter packages  # run gets flutter packages of project
        script: flutter packages pub get

      #      - name: Flutter Analyze
      #        script: flutter analyze
      - name: Flutter Unit Tests
        script: flutter test
        ignore_failure: true

      - name: Build Android App Bundle in Flutter
        script: |
          echo $BUILD_NUMBER 
          flutter build apk --release --build-name=1.0.$BUILD_NUMBER --build-number=$BUILD_NUMBER

      #      - name: Set up code signing settings on Xcode project
      #        script: |
      #          xcode-project use-profiles
      #      - name: Install pods
      #        script: |
      #          find . -name "Podfile" -execdir pod install \;
      #      - name: Flutter build ipa and automatic versioning
      #        script: |
      #          flutter build ipa --release build-name=1.0.$BUILD_NUMBER --build-number=$BUILD_NUMBER
      - name: Rename Artifacts 1
        script: |
          set TIME=$(date +%d_%m_%Y)
          set FILENAME=Svarupa_$TIME_1.0.$BUILD_NUMBER_b$BUILD_NUMBER.apk
          echo $FILENAME
          ls $ARTIFACTS_ANDROID_APK_RELEASE_PATH
          if [ ! -f "$ARTIFACTS_ANDROID_APK_RELEASE_PATH" ]; then
           mv "$ARTIFACTS_ANDROID_APK_RELEASE_PATH/*.apk" "$ARTIFACTS_ANDROID_APK_RELEASE_PATH/$FILENAME.apk"
          fi
    
    

    artifacts:
      - $ARTIFACTS_ANDROID_APK_RELEASE_PATH
      - build/**/outputs/**/mapping.txt
    publishing:
#      email:
#        recipients:
#          - sshivam@citridot.com
#        notify:
#          success: true
#          failure: false
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
          - group name 1
        submit_to_app_store: false
